create table experiments(
    expId int primary key GENERATED BY DEFAULT AS IDENTITY,
    expName text not null unique 
);

create table clients(
    clientId int primary key GENERATED BY DEFAULT AS IDENTITY,
    deviceToken uuid not null unique 
);

create table experimentExamples(
    exampleId  int primary key GENERATED BY DEFAULT AS IDENTITY,
    expId int not null references experiments(expId),
    optionName text not null unique,
    optionValue int not null 
);

create table clientExperimentResult(
    resultId int primary key GENERATED BY DEFAULT AS IDENTITY,
    exampleId int not null references experimentExamples(exampleId),
    clientId int not null references clients(clientId)
);